import { NextResponse } from "next/server";

// Balances are read from activity-log.json (generated by export script).
// For realtime Circle SDK calls, uncomment and import circle SDK.
// The current approach is simpler and avoids exposing API keys to browser.

import { readFileSync } from "fs";
import { join } from "path";

export async function GET() {
  try {
    const path = join(process.cwd(), "public", "activity-log.json");
    const raw = readFileSync(path, "utf-8");
    const data = JSON.parse(raw);
    return NextResponse.json({
      owner: data.wallets?.owner?.balance ?? "0",
      validator: data.wallets?.validator?.balance ?? "0",
    });
  } catch {
    return NextResponse.json({ owner: "0", validator: "0" });
  }
}
